Repository angular-hispano/angular, pull requests merged in 2020-10, with the labels that each got.

#276 Traducir ngmodules
  ngmodules.en.md
  ngmodules.md
Labels: hacktoberfest-accepted

#292 Traducir: marketing/features.html
  aio/content/marketing/features.html
Labels: hacktoberfest-accepted

#287 Translate two way binding
  aio/content/guide/two-way-binding.en.md
  aio/content/guide/two-way-binding.md
Labels: hacktoberfest-accepted

#288 Traducir Practical observable usage
  aio/content/guide/practical-observable-usage.en.md
  aio/content/guide/practical-observable-usage.md
Labels: hacktoberfest, hacktoberfest-accepted

#294 feat(termino): nuevo de cross platform
  aio/diccionario-de-términos.md
Labels: hacktoberfest-accepted

#295 fix: master/toh-pt3
  aio/content/tutorial/toh-pt3.md
Labels: bug

#297 test: fix aio e2e
  aio/tests/e2e/src/app.e2e-spec.ts
Labels: bug
