Repository angular-hispano/angular, pull requests merged in 2021-04, with the labels that each got.

#325 docs: fix presskit layout
  aio/content/marketing/presskit.html
Labels: bug

#346 docs: translate rx-library.md
  aio/content/guide/rx-library.en.md
  aio/content/guide/rx-library.md
Labels: Listo y Revisado

#340 Docs traducción de npm-packages.md
  aio/content/guide/npm-packages.en.md
  aio/content/guide/npm-packages.md
Labels: Listo y Revisado

#237 Testing utility apis
  aio/content/guide/testing-utility-apis.en.md
  aio/content/guide/testing-utility-apis.md
Labels: hacktoberfest-accepted
